### ISSUE TITLE
Bug Report: "Address already in use" when using TLS in Docker deployment

### ISSUE THREAD

**Issue by rbsherry** [drachtio/drachtio-server#433]
### Description
I am running Drachtio inside a Docker container.
- When I configure Drachtio to use TCP or UDP, it works perfectly.
- However, when I configure Drachtio to use TLS, it always fails with: `Address already in use`

even though:

- Nothing else is listening on the specified port (confirmed with lsof, netstat).
- I have tried multiple different ports (e.g., 5061, 6061, 7071, etc.) — same issue.

### drachtio.conf.xml
```
<drachtio>

    <admin port="9022" secret="cymru">127.0.0.1</admin>

    <tls key-file="/etc/drachtio/server.key" cert-file="/etc/drachtio/server.crt">
        <min-tls-version>1.2</min-tls-version>
        <key-file>/etc/drachtio/server.key</key-file>
        <cert-file>/etc/drachtio/server.crt</cert-file>
    </tls>

    <sip>
        <contacts>
            <contact>sips:*:5061;transport=tls</contact>
        </contacts>
    </sip>

</drachtio>

```

### Logs
```
Attaching to drachtio-server-1
drachtio-server-1  | 2025-04-29 06:42:34.579339 Starting drachtio version v0.9.3-rc3-3-gf79f87f4af
drachtio-server-1  | 2025-04-29 06:42:34.581361 Logging threshold:                     4
drachtio-server-1  | 2025-04-29 06:42:34.581815 DrachtioController::run listening for applications on tcp port 9022 only
drachtio-server-1  | 2025-04-29 06:42:34.597241 ClientController::threadFunc - ClientController: io_context run loop started (or restarted)
drachtio-server-1  | 2025-04-29 06:42:34.597780 DrachtioController::run - blacklist checking config
drachtio-server-1  | 2025-04-29 06:42:34.597814 DrachtioController::run - blacklist is disabled
drachtio-server-1  | 2025-04-29 06:42:34.597834 Prometheus support disabled
drachtio-server-1  | 2025-04-29 06:42:34.597937 tcp keep alives will be sent to clients every 45 seconds
drachtio-server-1  | 2025-04-29 06:42:34.598893 DrachtioController::run: starting sip stack on sips:*:5061;transport=tls
drachtio-server-1  | 2025-04-29 06:42:34.602835 tport_type_tls.c:229 tport_tls_init_master() tport_tls_init_master(0x555556172000): tls key file (TPTAG_TLS_CERTIFICATE_KEY_FILE) is required and not specified
drachtio-server-1  | 2025-04-29 06:42:34.603486 nta.c:2345 nta_agent_add_tport() nta: bind(*:5061;transport=tls): Address already in use
drachtio-server-1  | 2025-04-29 06:42:34.603762 DrachtioController::run: Error calling nta_agent_create
``` 

### docker-compose.yml
```
services:
  drachtio-server:
    image: drachtio/drachtio-server:latest
    ports:
      - "5061:5061/tcp"
    volumes:
      - ./certs/server.crt:/etc/drachtio/server.crt
      - ./certs/server.key:/etc/drachtio/server.key
      - ./drachtio.conf.xml:/etc/drachtio.conf.xml
```
